// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SlackProvider is an autogenerated mock type for the SlackProvider type
type SlackProvider struct {
	mock.Mock
}

// Notify provides a mock function with given fields: msg
func (_m *SlackProvider) Notify(msg string) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
